CREATE TABLE players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    normalized_name VARCHAR(100) NOT NULL,
    CONSTRAINT uk_players_normalized_name UNIQUE (normalized_name)
);

CREATE TABLE uno_games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    requested_rounds INTEGER NOT NULL,
    completed_rounds INTEGER NOT NULL,
    CONSTRAINT ck_uno_games_requested_rounds CHECK (requested_rounds > 0),
    CONSTRAINT ck_uno_games_completed_rounds CHECK (
        completed_rounds >= 0 AND completed_rounds <= requested_rounds
    ),
    CONSTRAINT ck_uno_games_timestamps CHECK (completed_at >= started_at)
);

CREATE TABLE game_players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    player_order INTEGER NOT NULL,
    final_score INTEGER NOT NULL,
    winner BOOLEAN NOT NULL,
    CONSTRAINT fk_game_players_game FOREIGN KEY (game_id) REFERENCES uno_games (id) ON DELETE CASCADE,
    CONSTRAINT fk_game_players_player FOREIGN KEY (player_id) REFERENCES players (id),
    CONSTRAINT uk_game_player_order UNIQUE (game_id, player_order),
    CONSTRAINT uk_game_player UNIQUE (game_id, player_id),
    CONSTRAINT ck_game_players_order CHECK (player_order >= 0),
    CONSTRAINT ck_game_players_score CHECK (final_score >= 0)
);

CREATE TABLE uno_rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INTEGER NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    winner_game_player_id BIGINT,
    points_awarded INTEGER NOT NULL,
    CONSTRAINT fk_uno_rounds_game FOREIGN KEY (game_id) REFERENCES uno_games (id) ON DELETE CASCADE,
    CONSTRAINT fk_uno_rounds_winner FOREIGN KEY (winner_game_player_id) REFERENCES game_players (id),
    CONSTRAINT uk_game_round_number UNIQUE (game_id, round_number),
    CONSTRAINT ck_uno_rounds_number CHECK (round_number > 0),
    CONSTRAINT ck_uno_rounds_status CHECK (status IN ('COMPLETED', 'SAFETY_LIMIT')),
    CONSTRAINT ck_uno_rounds_points CHECK (points_awarded >= 0),
    CONSTRAINT ck_uno_rounds_timestamps CHECK (completed_at >= started_at)
);

CREATE TABLE round_scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    round_id BIGINT NOT NULL,
    game_player_id BIGINT NOT NULL,
    score_before INTEGER NOT NULL,
    score_delta INTEGER NOT NULL,
    score_after INTEGER NOT NULL,
    CONSTRAINT fk_round_scores_round FOREIGN KEY (round_id) REFERENCES uno_rounds (id) ON DELETE CASCADE,
    CONSTRAINT fk_round_scores_game_player FOREIGN KEY (game_player_id) REFERENCES game_players (id),
    CONSTRAINT uk_round_game_player UNIQUE (round_id, game_player_id),
    CONSTRAINT ck_round_scores_before CHECK (score_before >= 0),
    CONSTRAINT ck_round_scores_delta CHECK (score_delta >= 0),
    CONSTRAINT ck_round_scores_after CHECK (score_after >= 0),
    CONSTRAINT ck_round_scores_total CHECK (score_after = score_before + score_delta)
);

CREATE INDEX ix_uno_games_completed_at ON uno_games (completed_at DESC);
CREATE INDEX ix_game_players_high_scores ON game_players (final_score DESC);
CREATE INDEX ix_game_players_winners ON game_players (player_id, winner);
